### ISSUE TITLE
Clean up and optimize data processing pipeline

### ISSUE THREAD

**Issue by emptyflash** [rmoscowitz/houston-book-link#10]
Ideally we should be able to run the overdrive data import relatively frequently. It would be nice if this automatically renewed oauth tokens, and ran quickly without bringing down the database (which probably means doing some update logic instead of just dropping all tables and starting over). 

Also I think we should probably either rewrite it in node, or rewrite the node parts in python, since it'll be annoying to update the data model right now.

**Comment by DanielJRutledge** [comment]
Eventually the data-processing task will become a server task just like starting and stopping the server, so the two should be the same codebase.
