### ISSUE TITLE
Add availability features

### ISSUE THREAD

**Issue by emptyflash** [rmoscowitz/houston-book-link#11]
I think since this is something that changes a lot, it make sense for the backend to act as a proxy to the Overdrive API

**Comment by rmoscowitz** [comment]
For future reference: https://developer.overdrive.com/apis/library-availability

**Comment by rmoscowitz** [comment]
a possible design for the UI:
![image](https://user-images.githubusercontent.com/3596827/27109164-bc810446-5066-11e7-9fa6-13d5e3d49682.png)

**Comment by rmoscowitz** [comment]
Related feature: an "available now" filter on the front end

**Comment by rmoscowitz** [comment]
Overdrive released a new version of its Availability API last week: http://developer.overdrive.com/apis/library-availability-new

**Comment by emptyflash** [comment]
What even did they actually add? I thought most of that stuff was in the API already.

**Comment by rmoscowitz** [comment]
Closing this issue. 😄
